a=input('enter a username=')
b=input('enter a mobile.no=')
c=input('enter a password=')
d=input('enter a email=')
print('username is', a)
print('moile.no is',b)
print('password is',c)
print('email is',d)
